---
apiVersion: v1
kind: Service
metadata:
  name: postgres-3
  labels:
    app: postgres-3
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-3

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-3-statefulset
spec:
  serviceName: "postgres-3"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-3
  template:
    metadata:
      labels:
        app: postgres-3
    spec:
      containers:
        - name: postgres-3
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: task11-config
                  key: DATABASE_3_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: task11-config
                  key: DATABASE_3_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task11-secret
                  key: DATABASE_3_PASSWORD_WITH_NEW_LINE
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres-3
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi